name: pypots
channels:
    - pytorch
    - pyg
    - conda-forge
    - nodefaults
dependencies:
    - conda-forge::python>=3.7.13
    - conda-forge::numpy
    - conda-forge::scipy
    - conda-forge::pandas>=1.4.1
    - conda-forge::scikit-learn
    - conda-forge::matplotlib
    - conda-forge::tensorboard
    - pytorch::pytorch>=1.10
    - conda-forge::pip
    - conda-forge::torchdiffeq
    - pyg::pyg
    - pip:
        - pycorruptor
        - tsdb
