name: pypots
channels:
    - pytorch
    - pyg
    - conda-forge
    - nodefaults
dependencies:
    - main::python=3.7.13
    - conda-forge::pip
    - conda-forge::numpy
    - conda-forge::scipy
    - conda-forge::pandas
    - conda-forge::scikit-learn
    - conda-forge::matplotlib
    - conda-forge::tensorboard
    - pytorch::pytorch>=1.10
    - pyg::pyg
    - pip:
        - torchdiffeq==0.2.3
        - pycorruptor==0.0.4
        - tsdb==0.0.7