blank_issues_enabled: true
version: 2.1
contact_links:
  - name: PyPOTS Community on Slack
    url: https://pypots-org.slack.com
    about: General usage questions, community discussions, and the development team are here.
